name: Running C tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-x86:
    # Do not ignore bash profile files. From:
    defaults:
      run:
        shell: bash -l {0}
        
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Clean previous builds
      run: |
        rm -rf ./build/
    - name: Configure CMake
      run: |
        cmake . -S ./ -B ./build/ -D CMAKE_BUILD_TYPE=Debug
    - name: Build
      run: |
        cmake --build ./build/ --target tests
        ./build/tests/tests
    - name: Run binary
      run: |
        ./build/tests/tests